language: node.js
node_js:
  - "node"

branches:
  only:
  - master

install:
  - yarn install

before_script:
  - npm run test:unit

script:
  - npm run build

notifications:
  email:
    on_failure: change
    on_success: change
